### PR TITLE
Feature/add btns to group page toolbar

### PR DESCRIPTION
**Pull request by data-doge**
[trello card](https://trello.com/c/6PSmmWuq/478-3-add-buttons-to-group-page-toolbar)

### admin btns replaced by more-btn as screen size is reduced

o fuk

### on more btn click, drawer opened with admin btns. cancel btn closes drawer

o fuk

### admin btns are only visible to admins of the current group

o fuk

### CODE REVIEW

**Comment by derekrazo** [comment]
Hey there - a couple things before merging this -

1) on mobile, when the drawer opens, the first option is automatically highlighted

2) can you make the buttons a bit smaller? I'm thinking 30px height and 13px text 

Looks great thought! Excited about it.

**Comment by data-doge** [comment]
@derekrazo 

the auto-highlighting is a bug currently on angular material's backlog: https://github.com/angular/material/issues/3352

will take more time than i want to take to hack around it -- r u cool with leavin the autohighlighting around for now?

**Comment by data-doge** [comment]
@derekrazo 

button sizes changed :+1:

**Comment by derekrazo** [comment]
fine with leaving the bug for now! Also I can't see the fixed button sizes
on staging?

**Comment by data-doge** [comment]
ahh fuck lol i forgot -- i'll deploy to staging now

**Pull request merged**
