### PR TITLE
change unpaid label text and color

### PR DESCRIPTION
**Pull request by jlopker**
screen shot 2017-03-21 at 5 57 38 pm

### CODE REVIEW

**Comment by jessykate** [comment]
@jlopker what do you think about making the label right-aligned? something like this (but in the grey color):

cobudget_

if you like this direction, i can do the mod if you like? LMK... i know you are neck-deep in [highcharts](https://github.com/cobudget/cobudget/issues/108) land :).

**Comment by jlopker** [comment]
hmmm i'm not the hugest fan of this... what's the problem that you see with the original placement?

**Comment by jessykate** [comment]
in a long list of unpaid buckets, when seen vertically, the tags form a jagged visual line, which feels like more work on the eyes and more work to skim for unpaid buckets. it strikes me as less chaotic visually to align them somehow, but i don't feel super strongly passionate about it...

**Comment by jlopker** [comment]
how about you try putting them at the far left. so inline with but before the name of the bucket creator.

**Comment by jlopker** [comment]
how about you try putting them at the far left? so inline with but before the name of the bucket creator.

**Comment by derekrazo** [comment]
Question:  can regular users see this tag? If so I think it will be confusing. My suggestion would be to make it admin-only

In that context, I think a solution here would be to de-emphasize the paid/unpaid tag and add a sort/filter to the top bar. So basically paid/ unpaid becomes text and if you want to sort by it you use the filter. There's really only one situation you want to see it right? You are checking what is paid out and not- therefor you just want a sorted list, not a browsable list.

**Comment by jlopker** [comment]
thanks @derekrazo! 

at the moment, everyone can see this tag. i don't think it's much visual clutter so doesn't seem like a problem to show to everyone but maybe it's a privacy concern? is it true that only admins would be interested in this information? i don't have a sense of this. 

so as it is implemented now, we sort the unpaid buckets to the top of the list. we don't make this obvious though so having an explicit sort function would be nice. @jessykate should we add a tix to the backlog for this?

**Comment by jessykate** [comment]
i like that. let's make a ticket for more formal sorting, and then see if we get feedback that it's confusing and/or whether people want to see the sorting functionality. in the meantime let's go ahead and push out this small update to the formatting of the label so that it's less oppressive :).

**Pull request merged**
