### PR TITLE
minor improvements to how scripts build

### PR DESCRIPTION
**Pull request by ahdinosaur**
most notable is adding [concatenify](http://npmjs.org/concatenify), which allows us to do things like [this](https://github.com/cobudget/cobudget-ui/blob/build-scripts/app/index.js#L38-L40) as @robguthrie was wishing for.

### CODE REVIEW

**Comment by robguthrie** [comment]
Marvellous! I think Loomio will look to adopt this build system soon.

**Comment by ahdinosaur** [comment]
@robguthrie sweet, keen to help with that. :)

**Comment by robguthrie** [comment]
@ahdinosaur I would love to have a chat with you about how one might go about creating a plugin architecture.

**Comment by ahdinosaur** [comment]
@robguthrie plugins for what? if you mean app-level modules, the general idea for a modular architecture is defining a format for modules (e.g. a module exports a function that takes in `opts` that have `x` and `y` and a `callback`) and making it easy to add and remove what modules are in use. (e.g. specify the modules you want to use in your app config). of course, ["One cannot make a system more modular by adding a modularity module"](https://twitter.com/dominictarr/status/613708900144148480), so modularity needs to be thought of in the context of the entire architecture, not as a separate component. but yeah, i'd love to learn more about what you mean because i have no idea.

**Comment by robguthrie** [comment]
Yea let's have a chat!

**Pull request merged**
