### PR TITLE
Feature/new user authentication system

### PR DESCRIPTION
**Pull request by euglazer**

### CODE REVIEW

**Comment by euglazer** [comment]
experimenting with a new, simpler auth system.

this auth system has 3 stages, and will be used on every page except the login-page.

these steps are:
1. authenticate user
  - the AuthenticateUser service uses ng-token-auth to check if there is a user stored in the session. if there is, returns a resolved promise with that user. otherwise, redirects to login page with toast, and returns a rejected promise.
2. check permissions for that user
  - the VerifyUserPermissions service takes care of this. it contains methods for each page requiring permissions. these methods check that a user is allowed access to the page. if allowed, returns a resolved promise. otherwise, returns a rejected promise.
3. fetch records
  - for now this is handled in the controller of each page, and performed only after steps 1 + 2 have resolved.

**Comment by ahdinosaur** [comment]
@euglazer makes sense. i'm wondering though, since you're doing permissions at the page-level instead of the model level, will there ever be a case that users can access the same page but have different model permissions? it seems like a more ideal solution is model-level permissions similar to the policies in the rails api, which then can be used to have the same effect as page-level permissions by checking if the user is allowed to fetch all the models required by the page.

**Comment by euglazer** [comment]
could you clarify what you mean by model-level?

**Comment by ahdinosaur** [comment]
@euglazer yup. i mean having a permission module per model module, [similar to the policies in the rails api](https://github.com/cobudget/cobudget-api/tree/master/app/policies). is that clear?

**Comment by euglazer** [comment]
@ahdinosaur 

sweet. yep, im planning to have a concept of permissions on both the client and server.

**Comment by euglazer** [comment]
@ahdinosaur 

for each page on the UI, the content is almost identical whether the current_user is an admin or not. the only things that change are minor bits of text and the presence/absence of certain buttons. as far as models go, the content served by the api is identical. 

on the backend, i am beginning to build a concept of permissions (that i hope to solidify with @robguthrie once he's well again). so permissions will be handled on both the page level and the model level

using the group-page as an example, the flow looks like this:

- user makes a request to `'/groups/22'`
  1. `AuthenticateUser` service checks that a user session exists.
    - if so, `VerifyUserPermissions` service's `.forGroup(groupId)` method is called with `groupId` of `22`
    - otherwise, redirected to login
  2. if user authenticated, `VerifyUserPermission.forGroup(groupId)` is called and ...
    - on backend, `GroupsController` checks that the group exists and that the user is a member of that group
      - if so, a `group` object is returned as JSON, and `VerifyUserPermission.forGroup(groupId)` returns a resolved promise with the requested group
      - otherwise, status code `404` or `401` is returned, and `VerifyUserPermission.forGroup(groupId)` returns a rejected promise
  3. once `VerifyUserPermission.forGroup(groupId)`'s promise is returned,
    - if promise resolved, records fetched
    - if promise rejected, records not fetched and 404 page rendered to the screen (similar to github: https://github.com/privateshit)

**Comment by ahdinosaur** [comment]
@euglazer awesome.

the way the alpha UI works is also interesting, somewhat similar to what you have in mind. every API call was intercepted, such that if there was ever a permission error from the API, it would redirect you to the login page. it meant we didn't have to write separate permission code since it was all tied in with the existing API calls, but also meant we couldn't write separate permission code. :smile: 

but it sounds like you know what you need and have a good plan that will work to meet your needs, nice work. :+1:

**Comment by robguthrie** [comment]
sounds great. Nice write up too. here's what we did in Loomio: https://github.com/loomio/loomio/blob/master/lineman/app/services/ability_service.coffee

**Pull request merged**
