### PR TITLE
Feature/123 archive refactor

### PR DESCRIPTION
**Pull request by jlopker**

### CODE REVIEW

**Comment by jlopker** [comment]
note: we should figure out if we want to change all live, archived buckets to a status of refunded. will affect some of the code.

**Comment by jessykate** [comment]
@jlopker cool! this seems to be working pretty well. i went through the various cases of archived + (fully-funded, not-fully-funded) and refunding, marking as paid, and the same for funded bu not-yet-archived... once i remembered to turn on mailcatcher all worked well :p. 

feedback is mostly on a design/UI level--

1. unify admin-blue: the blue of the 'mark as paid' button is different than the blue of the other admin functions (see eg. the blue color on the manage funds page). 
2. refund vs. archive - unify terminology and placement? 
    1. ‘archive’ option: it's not clear to me how people would know that "archiving" is mutually exclusive from "mark as paid." how could we communicate this better? i think this is somewhere that a user interview could help, if we can snag one easily. maybe derek might have suggestions on how he would approach this too. 
    2. "mark as paid" button should probably be styled in the same way as the other management buttons, and placed on the manage card, to maintain the separation between the management vs. status cards. what do you think? 
3. archived, funded, unpaid bucket —> “refund money” —> expected: some indication that the bucket HAD at one time been funded and was subsequently refunded. but i guess we don't actually _have_ this information, do we?   
    1. same for funded, unpaid bucket —> “archive”?

LMK what you think!

**Comment by jlopker** [comment]
thanks for the feedback @jessykate !
good eye on the blue- i updated it to match.
i styled the mark as paid btn after the start funding btn. i went back and forth on this and making it like the archive btn. i think either could work.. both actions seem a bit like a "move this bucket forward to the next step of the process" action so i thought it would make sense that they match
screen shot 2017-04-19 at 4 32 19 pm

to your last comment- we still have the datetime for `funded_at`. we could display this info on the archived, refunded bucket status card. we don't currently have a datetime for `unfunded_at` tho. do you think this would be useful information? maybe this is another thing we should user test!

**Comment by jessykate** [comment]
yay blue! thanks! 

regarding info on refunds...

> _to your last comment- we still have the datetime for funded_at. we could display this info on the archived, refunded bucket status card. we don't currently have a datetime for unfunded_at tho._

thinking about this, as we go forward, almost _any_ bucket that was archived will have been refunded (unless it was only an idea, or never received any contributions). since archiving is what causes the refund, we implicitly have the date that the refund happened at (it is the `archived_at` date). 

do we set `state=refunded` for partially funded AND fully funded buckets now (or are partially funded and then refunded buckets still set to `status-live`)? if so, we could use this to add _"and refunded"_ to the _"was archived on..."_ text, if it was indeed refunded. does that make sense, or is it too complicated?

regarding the wording and placement... 

* the difference with "mark as paid" is that only an admin can do this. so to me it feels like it should go on the manage card. perhaps we should get some additional opinions on this? 
* i still think we need a visual way to indicate that archive and mark as paid are two ways to complete a bucket. one idea could be to have a single "archive" button, which upon clicking presents a drop down option for either "refund" or "mark as paid". another option would be that the default is "mark as paid" with a secondary option to "cancel and return funds instead." which i think represents a sensible default. i don't really know UI design though. i bet there are other patterns.  

i am not sure the best next step-- to try something and then show it to users, or to talk to some users first...  i wish i had @derekrazo's 1337 sketch design skillz and could mock it up easily! 😭

**Comment by chime-mu** [comment]
I'm still confused about the word _archived_ - it just feels wrong.

In my mind buckets go through the phases and end up being either _Paid_ or _Cancelled_. These are words that clearly express what the state actually is.

I think the buckets previously known as _archived_ are buckets where we don't know if they in reality is _Paid_ or _Cancelled_. We need this state because we're tranferring from a system where that knowledge wasn't available. 

No new bucket should (in my mind) be able to enter the _archived_ state. Only old ones is in this state. Making this state explicit also make it possible for us to make the stats more informative - we can say how much is paid_out and how is in a unknown state. This is helpful for admins who need these sums.

And maybe we should change the name for the _archived_ state too.

**Comment by jessykate** [comment]
Looked through and tested locally. Looking good! I am going to merge this but am also in agreement with @chime-mu that the terminology around archiving is ambiguous. We could add a ticket for renaming this? Or we can wait to see if users indicate confusion? Lmk what you folks think.

**Comment by chime-mu** [comment]
Great @jessykate 

I've now received independent feedback from two people in BW7 about the possibility to cancel a bucket and refund the money, explicitly stating "you can only archive, not refund". So I'm going to create a story for the terminology change.

**Pull request merged**
