### PR TITLE
confirm account page updates

### PR DESCRIPTION
**Pull request by jlopker**
https://trello.com/c/c9Vd5Waw

* added confirm password field
* added uneditable email field

### CODE REVIEW

**Comment by jlopker** [comment]
@jessykate @chime-mu can one of you take a look?

you can go here to view the account creation page: http://localhost:9000/#/confirm_account?confirmation_token=DzNwUVScs8iZryZ_TYnhJg&email=juliana@greater.finance

specifically i'm interested in what you think of how the confirm password field works.

**Comment by jessykate** [comment]
ok did some testing... some minor form suggestions and then some larger observations about the general account creation process. 

* if i only fill in the first password field, it would be nice if the "confirm" field gave some feedback. currently the form just doesn't respond. 
* i like the immediate feedback when the passwords don't match
* the email that is coming through (in mailcatcher) when i invite a new user, doesn't seem to contain the email address? as a result when i click the link in the email, the email field in the form is blank, but uneditable, when i load the page. super confusing. 
* if i click the token again, ideally it would tell me it's expired. as it stands, it lets me try to set up the account and only tells me its expired after i hit submit (by redirecting me to the landing page and showing a small error in the bottom left hand corner). 

* i am not sure if this is a pre-existing bug/behaviour, but i also went to the homepage and created a new user and group from scratch. it prompts me for the group name, and when i hit enter, it immediately logs me in!! whaaaaaat. that's super weird because i haven't set a password yet. there IS an email that gets sent to me ("time to set up your account!") inviting me to set my name and password, but if i don't click it (as i imagine many people don't), then i'll have an account for which i never set a password. 

sorry i know you were just asking about the fields :), but i just noticed these other things while testing!

**Comment by jlopker** [comment]
yes, most of the things you're commenting on is the preexisting workflow. i documented the original workflow in the trello ticket here https://trello.com/c/c9Vd5Waw/7-as-a-new-user-logging-in-for-the-first-time-is-intuitive-and-logical-so-that-i-don-t-get-confused-and-drop-using-cobudget-and-or

... i've seen the whole don't set the password thing till later thing before, i think the idea is that it is less friction for people getting in to the product.

what kind of feedback would you like the confirm password field to give? like just showing the "passwords don't match" text as soon as the user starts typing their password in the create password field?

**Comment by jessykate** [comment]
@jlopker re feedback, maybe like the outline of the field could pulse red when someone skips it?

re backend-- ugh, duh. got it :). 

for the new groups -- daaaamn. i kind of have a hypothesis that that is a gotcha for a lot of people. what do you think? would it be hard to have them set their password when they create their group? or redirect them to a page that says "check your email!" etc...? both seem pretty standard but not sure how much work it would be.

**Comment by jlopker** [comment]
i don't think either of these would be hard.. i think having to go to your email is a lot friction so i'll investigate setting your password upfront. this would make the initial confirm account email unnecessary.. so we should think about what text we'd want in that email.

**Comment by jessykate** [comment]
@jlopker how about "thanks for creating an account! here's how to get involved, ask questions, etc..." ? :fried_shrimp:

**Comment by jlopker** [comment]
@jessykate did you see Derek's comment about the current flow? apparently he followed slack's flow. and he didn't say that he's gotten complaints about it. i propose we keep the flow the same for now unless we get user's complaining.

**Comment by derekrazo** [comment]
Keep it! :)

**Comment by jessykate** [comment]
Roger that. merging...!

**Pull request merged**
