### PR TITLE
added bitcoin and ethereum

### PR DESCRIPTION
**Pull request by jlopker**

### CODE REVIEW

**Comment by chime-mu** [comment]
@jlopker The change looks simple. However having to table with same information is bad practice. I suggest using the DRY principle as it reduce the cane of bugs, keeping complexity down and makes it easier to change going forward.

**Comment by chime-mu** [comment]
Actually I think having a table in the DB with a list of currencies and their symbols would be the right solution, instead of repeating it again and again - and instead having to redeploy code just because we're adding a currency.

**Comment by jlopker** [comment]
@chime-mu yes i agree about it being possible to make it more DRY, but creating a new table right now feels out of scope. i suggest we deploy as is and can think about creating a new table in the future.

**Comment by chime-mu** [comment]
I agree that creating a new table in the DB is not necessary. I however disagree that we should continue to have two of the tables with information in the UI. Moving that into a single table is step one. 

There's always a good reason to move things into the future and it always feels easier. And it just slowly erodes the code.

If this was an emergency fix, yes, I'll be happy to leave bad code as bad. But since this is in no way an emergency I can't see why we shouldn't build towards easily understandable and maintainable code.
At some point it might produce a bug a we will clean it up anyway - so why not do it now and get the advantage immediately?

As a general principle I would say always leave the code cleaner than you found it. Most projects slowly  move into worse and worse code because we don't take the necessary time to clean up all the time, every time, ref. broken window theory.

If you still disagree, we should do a call to clarify this.

**Comment by chime-mu** [comment]
Maybe we have different value sets here for what constitutes good software engineering practice and we should do some work on this in Barcelona? It would be good to talk about some of this stuff in person I think :)

**Comment by jlopker** [comment]
@chime-mu i moved the currencies definitions into a service! lmk what you think. i'm generally all about leaving code better than found, altho maybe at times i can be a tad bit lazy. thanks for keeping a close eye on it.

**Comment by chime-mu** [comment]
Looks good @jlopker :)

**Comment by chime-mu** [comment]
Merged but not deployed.

**Pull request merged**
